#!/usr/bin/env bash
# Does the following:
# create a file
# Displays "To infinity and beyond"
# Displays "I hate the kill command"
# Displays "Y U no love me?!"
# Deletes the file
#+ receiving a SIGQUIT or SIGTERM.

terminator() {
 rm /var/run/myscript.pid
 exit
}

echo "$$" > /var/run/myscript.pid

while true
do
 echo "To infinity and beyond"
 sleep 2
 trap 'echo "Y U no love me?!"' SIGINT
 trap 'echo "I hate the kill command" && terminator' SIGTERM
 trap 'terminator' SIGQUIT
done
