#!/usr/bin/env bash
# Displays "To infinity and beyond"
#+ a sleep 2 in between
# Displays "I am invincible!!!"

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo"I am invincible!!!"' SIGTERM
done
